import assert from "node:assert/strict";
import { execFileSync, execFile } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import test from "node:test";

// ponytail: postmaster refuses to start when the shell has no locale; C suits this --no-locale cluster.
process.env.LC_ALL ||= "C";

// Isolated real PostgreSQL cluster. Never reads deployment credentials.
test("FR-01~08: PostgreSQL migration, RLS, transactions and concurrent joins", async () => {
  const bin = process.env.PG_BIN ?? execFileSync("pg_config", ["--bindir"], { encoding: "utf8" }).trim();
  const root = mkdtempSync(join(tmpdir(), "devsprint-db-"));
  const args = ["-h", root, "-p", "55439", "-U", "postgres", "-d", "postgres", "-X", "-v", "ON_ERROR_STOP=1", "-At"];
  const sql = (query: string) => execFileSync(join(bin, "psql"), [...args, "-c", query], { encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] }).trim();
  const runAs = (id: string, query: string) => `begin; set local role authenticated; set local request.jwt.claim.sub = '${id}'; ${query}; commit;`;
  const user = (n: number) => `00000000-0000-0000-0000-${String(n).padStart(12, "0")}`;
  const fail = (query: string, message: string) => assert.throws(() => sql(query), error => String((error as { stderr?: string }).stderr ?? error).includes(message));
  const as = (n: number, query: string) => sql(runAs(user(n), query)).split("\n").filter(line => !["BEGIN","SET","COMMIT", ""].includes(line)).join("\n");
  const create = (n: number, capacity = 3) => as(n, `select public.create_meeting('study','테스트 도서관',${capacity},'개발 공부',${capacity === 2})`);
  const nextDay = (day: number) => `(current_date + ((${day} - extract(isodow from current_date)::integer + 7) % 7))`;
  let started = false;
  try {
    execFileSync(join(bin, "initdb"), ["-D", join(root, "data"), "-U", "postgres", "-A", "trust", "--no-locale", "-E", "UTF8"], { stdio: "pipe" });
    execFileSync(join(bin, "pg_ctl"), ["-D", join(root, "data"), "-l", join(root, "server.log"), "-o", `-k ${root} -p 55439 -h ''`, "-w", "start"], { stdio: "pipe" });
    started = true;
    sql(`create role anon; create role authenticated; create schema auth;
      create table auth.users(id uuid primary key, email text, email_confirmed_at timestamptz);
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema public, auth to anon, authenticated; grant execute on function auth.uid() to anon, authenticated;`);
    sql(readFileSync(new URL("../supabase/migrations/202609130001_mvp.sql", import.meta.url), "utf8"));
    sql(readFileSync(new URL("../supabase/migrations/202609220001_revision.sql", import.meta.url), "utf8"));
    fail(`insert into auth.users values('${user(1)}','host@school.test',now())`, "SCHOOL_EMAIL_REQUIRED");
    sql(`insert into public.app_settings(id,school_name,email_domain,semester,weekdays,period_count,retention_policy,public_places) values(true,'테스트 학교','school.test','테스트 학기',array[1,2,3,4,5],8,'테스트가 끝나면 데이터를 즉시 삭제합니다.',array['테스트 도서관']);`);
    fail(`insert into auth.users values('${user(9)}','a@school.test.evil',now())`, "SCHOOL_EMAIL_REQUIRED");
    for (let n=1; n<=6; n++) sql(`insert into auth.users values('${user(n)}','student${n}@school.test',${n === 6 ? "null" : "now()"})`);
    fail(runAs(user(6), "select public.get_meetings()"), "AUTH_REQUIRED");
    fail("set role anon; select public.get_meetings()", "permission denied");
    fail(runAs(user(1), "select public.create_meeting('study','테스트 도서관',2,'개발 공부')"), "PROFILE_REQUIRED");
    for (let n=1; n<=5; n++) as(n, `select public.save_profile('학생${n}',array[101,102,203])`);
    fail(runAs(user(1), "select public.save_profile('이름',array[109])"), "INVALID_SLOTS");
    fail(runAs(user(1), "select public.save_profile('이름',array[null]::integer[])"), "INVALID_SLOTS");
    fail(runAs(user(1), "select public.save_profile('',array[101])"), "INVALID_NAME");
    fail(runAs(user(1), `update public.profiles set display_name='권한 우회' where id='${user(2)}'`), "permission denied");
    fail(runAs(user(1), "select * from public.meeting_members"), "permission denied");
    fail(runAs(user(1), "select * from auth.users"), "permission denied");
    fail(runAs(user(1), `select private.effective_slots(gen_random_uuid(),'${user(2)}')`), "permission denied");
    assert.equal(as(1, "select count(*) from public.availability"), "1");
    assert.equal(as(1, `select count(*) from public.profiles where id='${user(2)}'`), "0");
    fail(runAs(user(1), "select public.create_meeting('chat','테스트 도서관',2,'개발 공부')"), "INVALID_KIND");
    fail(runAs(user(1), "select public.create_meeting('study','테스트 도서관',1,'개발 공부')"), "INVALID_CAPACITY");
    fail(runAs(user(1), "select public.create_meeting('study','임의 장소',3,'개발 공부')"), "INVALID_PLACE");
    fail(runAs(user(1), "select public.create_meeting('study','테스트 도서관',2,'개발 공부')"), "PAIR_CHOICE_REQUIRED");
    const meeting = create(1);
    fail(runAs(user(1), `select public.confirm_meeting('${meeting}',101,${nextDay(1)})`), "WAIT_FOR_MEMBER");
    let record = JSON.parse(as(2, `select public.get_meetings('${meeting}')`))[0];
    assert.deepEqual(record.common_slots, [], "single host's full timetable stays private");
    assert.deepEqual(record.my_overlap, [101,102,203]);
    as(2, "select public.save_profile('학생2',array[102,203])");
    as(2, `select public.join_meeting('${meeting}')`);
    as(2, `select public.join_meeting('${meeting}')`);
    record = JSON.parse(as(1, `select public.get_meetings('${meeting}')`))[0];
    assert.equal(record.member_count, 2);
    assert.deepEqual(record.common_slots, [102,203]);
    assert.equal(record.members[0].name, "참여자");
    assert.equal(record.topic, "개발 공부");
    assert(!JSON.stringify(record).includes("@school.test"));
    fail(runAs(user(2), `select public.confirm_meeting('${meeting}',102,${nextDay(1)})`), "HOST_ONLY");
    fail(runAs(user(1), `select public.confirm_meeting('${meeting}',101,${nextDay(1)})`), "NO_COMMON_SLOT");
    as(1, `select public.confirm_meeting('${meeting}',102,${nextDay(1)})`);
    as(3, "select public.save_profile('학생3',array[203])");
    fail(runAs(user(3), `select public.join_meeting('${meeting}')`), "TIME_CONFLICT");
    as(2, "select public.save_profile('학생2',array[203])");
    record = JSON.parse(as(1, `select public.get_meetings('${meeting}')`))[0];
    assert.equal(record.confirmed_slot, null, "availability edit invalidates stale confirmation");
    as(1, `select public.confirm_meeting('${meeting}',203,${nextDay(2)})`);
    as(3, `select public.join_meeting('${meeting}')`);
    fail(runAs(user(4), `select public.join_meeting('${meeting}')`), "MEETING_FULL");

    const race = create(1, 2);
    const concurrent = await Promise.allSettled([4,5].map(n => promisify(execFile)(join(bin,"psql"), [...args,"-c",runAs(user(n), `select public.join_meeting('${race}'); select pg_sleep(0.1)`)])));
    assert.equal(concurrent.filter(result => result.status === "fulfilled").length, 1, "exactly one final seat succeeds");
    assert.equal(sql(`select count(*) from public.meeting_members where meeting_id='${race}'`), "2");
    const alternative = create(3);
    as(4, `select public.join_meeting('${alternative}')`);
    fail(runAs(user(1), `select public.get_comments('${alternative}')`), "MEMBER_ONLY");
    as(3, `select public.add_comment('${alternative}','도서관에서 만나요')`);
    assert.equal(JSON.parse(as(4, `select public.get_comments('${alternative}')`))[0].body, "도서관에서 만나요");
    as(4, `select public.set_meeting_availability('${alternative}',array[101])`);
    assert.deepEqual(JSON.parse(as(3, `select public.get_meetings('${alternative}')`))[0].common_slots, []);
    as(3, `select public.propose_time('${alternative}',101,${nextDay(1)})`);
    fail(runAs(user(5), `select public.join_meeting('${alternative}')`), "PROPOSAL_PENDING");
    as(4, `select public.accept_time('${alternative}')`);
    assert.equal(JSON.parse(as(3, `select public.get_meetings('${alternative}')`))[0].confirmed_slot, 101);
    as(3, `select public.remove_member('${alternative}','${user(4)}')`);
    assert.equal(JSON.parse(as(3, `select public.get_meetings('${alternative}')`))[0].confirmed_slot, null);
    fail(runAs(user(4), `select public.join_meeting('${alternative}')`), "MEETING_NOT_FOUND");
    const pair = create(4, 2);
    as(5, `select public.join_meeting('${pair}')`);
    as(4, `select public.confirm_meeting('${pair}',101,${nextDay(1)})`);
    as(1, `select public.report_problem(null,'${user(4)}','문제 행동')`);
    as(3, `select public.report_problem(null,'${user(4)}','문제 행동')`);
    as(5, `select public.report_problem(null,'${user(4)}','문제 행동')`);
    fail(runAs(user(4), "select public.create_meeting('study','테스트 도서관',3,'새 모임')"), "ACCOUNT_RESTRICTED");
    as(5, "select public.delete_account()");
    assert.equal(JSON.parse(as(4, `select public.get_meetings('${pair}')`))[0].confirmed_slot, null);
    as(2, "select public.save_profile('학생2','{}'::integer[])");
    record = JSON.parse(as(1, `select public.get_meetings('${meeting}')`))[0];
    assert.deepEqual(record.common_slots, []);
    assert.equal(record.confirmed_slot, null);
    as(2, "select public.delete_account()");
    assert.equal(sql(`select count(*) from public.availability where user_id='${user(2)}'`), "0");
    fail(runAs(user(2), "select public.get_meetings()"), "AUTH_REQUIRED");
    as(3, `select public.block_user('${user(1)}')`);
    assert.equal(JSON.parse(as(3, "select public.get_meetings() ")).some((item: { id: string }) => item.id === meeting), false);
    as(1, "select public.delete_account()");
    assert.equal(sql(`select count(*) from public.meetings where id='${meeting}'`), "0");
    assert.equal(sql(`select count(*) from public.meeting_members where meeting_id='${meeting}'`), "0");
    sql("update public.app_settings set semester='다음 학기'");
    fail(runAs(user(3), "select public.create_meeting('study','테스트 도서관',3,'새 모임')"), "PROFILE_REQUIRED");
    assert.deepEqual(JSON.parse(as(3,"select public.get_meetings()")), []);
  } finally {
    if (started) execFileSync(join(bin,"pg_ctl"), ["-D",join(root,"data"),"-m","immediate","-w","stop"], { stdio: "pipe" });
    rmSync(root, { recursive: true, force: true });
  }
});
